# Deployment do Conversão Peso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: hernanisoares/keycloak:latest
          ports:
            - containerPort: 80
            
---

# Service da aplicação web

apiVersion: v1
kind: Service
metadata: 
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - port: 80
    protocol: TCP
    name: http
  type: LoadBalancer