name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker build and push
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./keycloak-original/quarkus/container
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: |
            hernanisoares/keycloak:latest
            hernanisoares/keycloak:${{ github.run_number }}
          
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_K8S }}
#           context: <context name> # current-context from kubeconfig is used as default
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v3.0
        with:
          images: hernanisoares/keycloak:${{ github.run_number }}
          manifests: |
            k8s/deployment.yaml